[colors.bright]
black = "#6b7089"
blue = "#91acd1"
cyan = "#95c4ce"
green = "#c0ca8e"
magenta = "#ada0d3"
red = "#e98989"
white = "#d2d4de"
yellow = "#e9b189"

[colors.cursor]
cursor = "#c6c8d1"
text = "#161821"

[colors.normal]
black = "#161821"
blue = "#84a0c6"
cyan = "#89b8c2"
green = "#b4be82"
magenta = "#a093c7"
red = "#e27878"
white = "#c6c8d1"
yellow = "#e2a478"

[colors.primary]
background = "#161821"
foreground = "#c6c8d1"

[colors.selection]
background = "#272c42"
text = "#c6c8d1"

[colors.vi_mode_cursor]
cursor = "#c6c8d1"
text = "#161821"

[env]
TERM = "alacritty"

[font]
size = 12

[font.bold]
family = "PlemolJP35 Console NF"
style = "Bold"

[font.bold_italic]
family = "PlemolJP35 Console NF"
style = "Bold Italic"

[font.italic]
family = "PlemolJP35 Console NF"
style = "Italic"

[font.normal]
family = "PlemolJP35 Console NF"
style = "Regular"

[terminal.shell]
args = ["--login", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[window]
decorations = "full"
opacity = 0.85
startup_mode = "Windowed"

[terminal]
