name: "Install composite action"
description: "Checks out the repository and install tools"

inputs:
  commitHash:
    description: 'Commit hash for CI'
    required: true

runs:
  using: "composite"
  steps:
  - name: "Checkout"
    uses: actions/checkout@v3
    with:
      ref: ${{ inputs.commitHash }}
  - name: Run install.sh
    shell: bash
    run: ./script/install.sh
  - name: Run setup task
    shell: bash
    env:
      GIT_NAME: saku
      GIT_EMAIL: example@example.com
      PYTHON_VERSION: 3.10.2
      GO_VERSION: 1.17.7
      NODE_VERSION: 16.14.0
    run: |
      cargo make --makefile script/task.toml setup \
        -e GIT_NAME="$GIT_NAME" \
        -e GIT_EMAIL="$GIT_EMAIL" \
        -e PYTHON_VERSION="$PYTHON_VERSION" \
        -e GO_VERSION="$GO_VERSION" \
        -e NODE_VERSION="$NODE_VERSION"
#  - name: Run update task
#    shell: bash
#    env:
#      NPM_UPDATE_VERSION: "7.6.0"
#    run: |
#      cargo make --makefile script/task.toml update \
#        -e NPM_UPDATE_VERSION="$NPM_UPDATE_VERSION"
