[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  let g:NERDTreeShowHidden=1
  let g:NERDTreeWinSize = 20
  nnoremap <silent><C-e> :NERDTreeToggle<CR>
  nnoremap <F9> :NERDTree ~/Downloads<CR>
  nnoremap <F8> :NERDTree ~/Desktop<CR>
  noremap dir :NERDTree<CR>
  nnoremap sd :<C-u>tabnew<CR>:NERDTree<CR>
  let g:NERDTreeIgnore=['\.DS_Store$']
'''

[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = '''
  colorscheme onedark
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  call RequirePlugin('lightline.vimrc')
'''

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'kana/vim-submode'
hook_add = '''
  call submode#enter_with('bufmove', 'n', '', 's>', '<C-w>>')
  call submode#enter_with('bufmove', 'n', '', 's<', '<C-w><')
  call submode#enter_with('bufmove', 'n', '', 's+', '<C-w>+')
  call submode#enter_with('bufmove', 'n', '', 's-', '<C-w>-')
  call submode#map('bufmove', 'n', '', '>', '<C-w>>')
  call submode#map('bufmove', 'n', '', '<', '<C-w><')
  call submode#map('bufmove', 'n', '', '+', '<C-w>+')
  call submode#map('bufmove', 'n', '', '-', '<C-w>-')
'''

[[plugins]]
repo = 'voldikss/vim-floaterm'
on_cmd = 'FloatermNew'
on_func = 'floaterm#'
hook_add = '''
  " exit してもウィンドウが残ると閉じないといけないので
  let g:floaterm_autoclose = 1

  nnoremap <expr> <C-k> floaterm#buflist#first() == -1 ? '<Cmd>FloatermNew<CR>' : '<Cmd>FloatermToggle<CR>'
  inoremap <expr> <C-k> floaterm#buflist#first() == -1 ? '<Cmd>FloatermNew<CR>' : '<Cmd>FloatermToggle<CR>'
'''
hook_source = '''
  autocmd User FloatermOpen tnoremap <buffer> <silent> <C-k> <C-\><C-n>:FloatermToggle<CR>
  autocmd User FloatermOpen tnoremap <buffer> <silent> <C-t> <C-\><C-n>:FloatermNew<CR>
  autocmd User FloatermOpen tnoremap <buffer> <silent> <C-]> <C-\><C-n>:FloatermNext<CR>
  autocmd User FloatermOpen tnoremap <buffer> <silent> <C-[> <C-\><C-n>:FloatermPrev<CR>
  autocmd QuitPre * FloatermKill!
'''

[[plugins]]
repo = 'vim-scripts/AnsiEsc.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'glidenote/memolist.vim'
hook_add = '''
  call RequirePlugin('memolist.vimrc')
'''

[[plugins]]
repo = 'osyo-manga/vim-over'
hook_add = '''
nnoremap <silent> <Leader>m :OverCommandLine<CR>
" カーソル下の単語をハイライト付きで置換
nnoremap sub :OverCommandLine<CR>%s/<C-r><C-w>//g<Left><Left>
" コピーした文字列をハイライト付きで置換
nnoremap subp y:OverCommandLine<CR>%s!<C-r>=substitute(@0, '!', '\\!', 'g')<CR>!!gI<Left><Left><Left>
'''

[[plugins]]
repo = 'junegunn/fzf'
hook_post_update = '''
  if !isdirectory(expand('~/.fzf'))
    execute '!git clone https://github.com/junegunn/fzf.git ~/.fzf'
    execute '!~/.fzf/install --all'
  endif
'''
hook_add = '''
  nnoremap <leader>f :call FZFJumpFileFunc(expand("<cfile>"))<CR>
  vnoremap <leader>f :call FZFJumpFileFunc(GetSelectionText())<CR>
  call RequirePlugin('fzf.vimrc')
'''

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
  call RequirePlugin('ripgrep.vimrc')
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
hook_add = '''
  call RequirePlugin('coc.vimrc')
'''

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/ddu.vim'
hook_add = '''
  call RequirePlugin('ddu.vimrc')
'''

[[plugins]]
repo = 'Shougo/ddu-ui-ff'

[[plugins]]
repo = 'Shougo/ddu-kind-file'

[[plugins]]
repo = 'Shougo/ddu-source-file'

[[plugins]]
repo = 'Shougo/ddu-source-register'

[[plugins]]
repo = 'kuuote/ddu-source-mr'

[[plugins]]
repo = 'lambdalisue/mr.vim'

[[plugins]]
repo = 'shun/ddu-source-buffer'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'

[[plugins]]
repo = 'Shougo/ddu-commands.vim'
