### Added by Zinit's installer
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
    print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{219} Initiative Plugin Manager (%F{33}zdharma/zinit%F{220})…%f"
    command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
    if ! command git clone https://github.com/zdharma-continuum/zinit "$HOME/.zinit/bin"; then    
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b"
    else
        print -P "%F{160}▓▒░ The clone has failed.%f%b"
    fi
fi

source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit chpwd_recent_dirs cdr add-zsh-hook
add-zsh-hook chpwd chpwd_recent_dirs
# shellcheck disable=SC2034,SC2154
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit load zdharma-continuum/history-search-multi-word
zinit load zsh-users/zsh-completions

zinit light-mode for \
    zdharma-continuum/z-a-rust \
    zdharma-continuum/z-a-as-monitor \
    zdharma-continuum/z-a-patch-dl \
    zdharma-continuum/z-a-bin-gem-node \
    zsh-users/zsh-autosuggestions \
    zdharma-continuum/fast-syntax-highlighting \
    zsh-users/zaw

zinit for \
    zdharma-continuum/history-search-multi-word \
    zsh-users/zsh-completions

# fpath for completions
fpath=("$HOME/.zinit/completions" "${fpath[@]}")

## asdf
if [ -f "$HOME/.asdf/asdf.sh" ]; then
  zinit ice lucid as'program' src'asdf.sh'
  zinit load asdf-vm/asdf

  if [[ -n "$ASDF_DIR" ]]; then
    fpath=("$ASDF_DIR/completions" "${fpath[@]}")
  elif [ -e /usr/local/share/zsh-completions ]; then
    fpath=(/usr/local/share/zsh-completions "${fpath[@]}")
  fi
fi

## direnv
if type direnv > /dev/null 2>&1; then
  zinit ice lucid from'gh-r' as'program' mv'direnv* -> direnv' \
      atclone'./direnv hook zsh > zhook.zsh' atpull'%atclone' \
      pick'direnv' src='zhook.zsh'
  zinit load direnv/direnv
  export DIRENV_WARN_TIMEOUT=1h  # env 作成に時間が掛かると出てくる警告を抑える
fi

## ssh-agent
# Start SSH agent and load keys on login
if [ -z "$(pgrep ssh-agent)" ]; then
    eval "$(ssh-agent -s)"
    ssh-add --apple-load-keychain
fi

# zsh setting
## History
HISTFILE=~/.zsh_history
HISTSIZE=10000               # history size in memory
# shellcheck disable=SC2034
SAVEHIST=100000              # history size in file
setopt hist_ignore_all_dups  # 重複するコマンド行は古い方を削除
setopt hist_ignore_dups      # 直前と同じコマンドラインはヒストリに追加しない
setopt inc_append_history    # 履歴をインクリメンタルに追加
setopt share_history         # コマンド履歴ファイルを共有する
setopt append_history        # 履歴を追加 (毎回 .zsh_history を作るのではなく)
setopt hist_no_store         # historyコマンドは履歴に登録しない
setopt hist_reduce_blanks    # 余分な空白は詰めて記録

## beep音を鳴らさない
setopt no_beep
## cd 時に自動で push
setopt auto_pushd
## 同じディレクトリを pushd しない
setopt pushd_ignore_dups

autoload -U compinit
compinit
### End of Zplugin's installer chunk

bindkey '^r' zaw-history
bindkey '^zd' zaw-cdr
bindkey '^zb' zaw-git-branches

# zstyle
zstyle ':zaw:history' default zaw-callback-replace-buffer
zstyle ':chpwd:*' recent-dirs-max 5000
zstyle ':chpwd:*' recent-dirs-default yes
zstyle ':completion:*' recent-dirs-insert both
zstyle ':filter-select' case-insensitive yes

# environment variables
## for editor
# export EDITOR=vim

## for word delete and move.
export WORDCHARS="*?_[]~&;=!#$%^(){}<>"

## for flutter
export PATH=$PATH:$HOME/flutter/bin
## for dart tools
export PATH="$PATH:$HOME/.pub-cache/bin"

## for go
export GHQ_ROOT=$HOME/ghq
export GOROOT=$HOME/go

## for ruby
[[ -d ~/.rbenv  ]] && export PATH=${HOME}/.rbenv/bin:${PATH} && eval "$(rbenv init -)"

## for homebrew
export PATH="$PATH:/opt/homebrew/bin:/usr/local/sbin"

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_OPTS="--height 50% --layout=reverse --border"

## ghq cd
function gcd() {
  local distination
  distination=$(ghq list | fzf +m --query "$LBUFFER" --prompt="Select Repository > ")
  if [ "$distination" = "" ]; then
    zle redisplay
    return 1
  fi
  cd "$GHQ_ROOT/$distination" || exit
}

## gcloud
PATH=$HOME/google-cloud-sdk/bin:$PATH
# The next line updates PATH for the Google Cloud SDK.
if [ -f "$HOME/google-cloud-sdk/path.zsh.inc" ]; then . "$HOME/google-cloud-sdk/path.zsh.inc"; fi

# The next line enables shell command completion for gcloud.
if [ -f "$HOME/google-cloud-sdk/completion.zsh.inc" ]; then . "$HOME/google-cloud-sdk/completion.zsh.inc"; fi

## profile
if [ -f "$HOME/.profile" ]; then . "$HOME/.profile"; fi

# Aliases
## git
alias g='git'

## ls
if type exa > /dev/null 2>&1; then
	alias ls='exa'
else
  alias ls='ls -G'
fi

## find
if type fd > /dev/null 2>&1; then
	alias find='fd'
fi

## cat
if type bat > /dev/null 2>&1; then
	alias cat='bat'
fi

## brew
alias brew='env PATH="${PATH//.asdf/shims:/}" brew'

## kubectl
alias k='kubectl'

## terraform
alias t='terraform'

## rm
alias rm='rm -i'

## ruby(bundler)
alias bundler='bundle install --path=vendor/bundle --binstubs=vendor/bin'
source "${XDG_CONFIG_HOME:-$HOME/.config}/asdf-direnv/zshrc"

# For rancher desktop
export PATH="$HOME/.rd/bin:$PATH"

## For kube
export USE_GKE_GCLOUD_AUTH_PLUGIN=True
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
if [ ! -e "$HOME/.zinit/completions/_kubectl" ]; then
  kubectl completion zsh > "$HOME/.zinit/completions/_kubectl"
fi

## For Docker.app
if [ -e /Applications/Docker.app ]; then
  if [ ! -e "$HOME/.zinit/completions/_docker" ]; then
    ln -s /Applications/Docker.app/Contents/Resources/etc/docker.zsh-completion "$HOME/.zinit/completions/_docker"
  fi
  if [ ! -e "$HOME/.zinit/completions/_docker-compose" ]; then
    ln -s /Applications/Docker.app/Contents/Resources/etc/docker-compose.zsh-completion "$HOME/.zinit/completions/_docker-compose"
  fi
fi

# pnpm
export PNPM_HOME="$HOME/Library/pnpm"
export PATH="$PNPM_HOME:$PATH"
# pnpm end

