name: linux

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  setup-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/composite-action
