name: linux

on:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  setup-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/composite-action
