name: macos

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  setup-macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/composite-action
